#!/usr/bin/env bash
# Bash completion for ai-cli and wrapped/native tool aliases.
# Generated by ai_cli.completion_gen

_ai_cli_is_wrapped_cmd() {
  local cmd="$1"
  local resolved
  resolved="$(command -v "$cmd" 2>/dev/null || true)"
  [[ "$resolved" == "$HOME/.ai-cli/bin/$cmd" ]]
}

_ai_cli_fill_tool_data() {
  local tool="$1"
  native_flags=""
  native_subcommands=""
  file_flags=""
  dir_flags=""
  case "$tool" in
    claude)
      native_flags="--add-dir --agent --agents --allow-dangerously-skip-permissions --allowedTools --append-system-prompt --betas --chrome --continue --dangerously-skip-permissions --debug --debug-file --disable-slash-commands --disallowedTools --effort --fallback-model --file --fork-session --from-pr --help --ide --include-partial-messages --input-format --json-schema --max-budget-usd --mcp-config --mcp-debug --model --no-chrome --no-session-persistence --output-format --permission-mode --plugin-dir --print --replay-user-messages --resume --session-id --setting-sources --settings --strict-mcp-config --system-prompt --tmux --tools --verbose --version --worktree -c -d -h -p -r -v -w"
      native_subcommands="auth doctor mcp plugin setup-token"
      file_flags="--debug-file --file --json-schema --mcp-config --settings"
      dir_flags="--add-dir --plugin-dir"
      ;;
    codex)
      native_flags="--add-dir --ask-for-approval --cd --config --dangerously-bypass-approvals-and-sandbox --disable --enable --full-auto --help --image --local-provider --model --no-alt-screen --oss --profile --sandbox --search --version -C -V -a -c -h -i -m -p -s"
      native_subcommands="exec review login logout mcp mcp-server app-server app completion sandbox debug apply resume fork cloud features help"
      file_flags="--config --local-provider --profile"
      dir_flags="--add-dir"
      ;;
    copilot)
      native_flags="--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --alt-screen --autopilot --available-tools --banner --bash-env --config-dir --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --enable-all-github-mcp-tools --excluded-tools --experimental --help --interactive --log-dir --log-level --max-autopilot-continues --model --mouse --no-alt-screen --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --plain-diff --prompt --resume --screen-reader --secret-env-vars --share --share-gist --silent --stream --version --yolo -h -i -p -s -v"
      native_subcommands="init plugin update version commands config environment logging permissions"
      file_flags="--additional-mcp-config"
      dir_flags="--add-dir --config-dir --log-dir"
      ;;
    gemini)
      native_flags="--accept-raw-output-risk --allowed-mcp-server-names --allowed-tools --approval-mode --debug --delete-session --experimental-acp --extensions --help --include-directories --list-extensions --list-sessions --model --output-format --policy --prompt --prompt-interactive --raw-output --resume --sandbox --screen-reader --version --yolo -d -e -h -i -l -m -o -p -r -s -v -y"
      native_subcommands=""
      file_flags=""
      dir_flags=""
      ;;
    *) ;;
  esac
}

_ai_cli_tool_completion_impl() {
  local tool="$1"
  local cur prev words cword
  _init_completion 2>/dev/null || {
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    words=("${COMP_WORDS[@]}")
    cword=$COMP_CWORD
  }

  _ai_cli_fill_tool_data "$tool"

  local flags="$native_flags"
  if _ai_cli_is_wrapped_cmd "$tool"; then
    flags="$flags --ai-cli-system-instructions-file --ai-cli-system-instructions-text --ai-cli-canary-rule --ai-cli-passthrough --ai-cli-debug-requests --ai-cli-developer-instructions-mode --ai-cli-no-startup-context"
  fi

  case " $file_flags " in
    *" $prev "*) COMPREPLY=($(compgen -f -- "$cur")); return ;;
  esac
  case " $dir_flags " in
    *" $prev "*) COMPREPLY=($(compgen -d -- "$cur")); return ;;
  esac

  if [[ "$cur" == -* ]]; then
    COMPREPLY=($(compgen -W "$flags" -- "$cur"))
    return
  fi

  local i subcommand=""
  for (( i=1; i < cword; i++ )); do
    if [[ "${words[i]}" != -* ]]; then
      subcommand="${words[i]}"
      break
    fi
  done

  if [[ -z "$subcommand" ]]; then
    COMPREPLY=($(compgen -W "$native_subcommands" -- "$cur"))
    COMPREPLY+=($(compgen -d -- "$cur"))
  fi
}

_ai_cli_completion() {
  local cur prev words cword
  _init_completion 2>/dev/null || {
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    words=("${COMP_WORDS[@]}")
    cword=$COMP_CWORD
  }

  # Top-level subcommand completions with descriptions
  if [[ $cword -eq 1 ]]; then
    COMPREPLY=($(compgen -W "claude codex copilot gemini menu status system prompt-edit session traffic update completions help" -- "$cur"))
    return
  fi

  local cmd="${words[1]}"
    case "$cmd" in
    claude|codex|copilot|gemini)
      _ai_cli_tool_completion_impl "$cmd"
      return ;;
    system)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "prompt claude codex copilot gemini" -- "$cur"))
      else
        COMPREPLY=($(compgen -W "claude codex copilot gemini" -- "$cur"))
      fi
      return ;;
    session)
      case "$prev" in
        --agent) COMPREPLY=($(compgen -W "all claude codex copilot gemini" -- "$cur")); return ;;
        --tail) return ;;
      esac
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "--agent --all --list --grep --tail --tools --raw" -- "$cur"))
      else
        COMPREPLY=($(compgen -f -- "$cur"))
      fi
      return ;;
    traffic)
      case "$prev" in
        --caller|-c) COMPREPLY=($(compgen -W "claude copilot codex gemini" -- "$cur")); return ;;
        --sort) COMPREPLY=($(compgen -W "date address" -- "$cur")); return ;;
        --db) COMPREPLY=($(compgen -f -- "$cur")); return ;;
        --host|--search|-s|--limit|-n|--detail|-d) return ;;
      esac
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "--caller --host --search --api --sort --limit --db --plain --detail" -- "$cur"))
      fi
      return ;;
    update)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "--all --dry-run --list --method --list-methods" -- "$cur"))
      else
        COMPREPLY=($(compgen -W "claude codex copilot gemini" -- "$cur"))
      fi
      return ;;
    completions)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "generate" -- "$cur"))
      elif [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "--shell" -- "$cur"))
      fi
      return ;;
  esac
}

_ai_cli_claude_completion() { _ai_cli_tool_completion_impl claude; }
_ai_cli_codex_completion() { _ai_cli_tool_completion_impl codex; }
_ai_cli_copilot_completion() { _ai_cli_tool_completion_impl copilot; }
_ai_cli_gemini_completion() { _ai_cli_tool_completion_impl gemini; }

complete -F _ai_cli_completion ai-cli
complete -F _ai_cli_claude_completion claude
complete -F _ai_cli_codex_completion codex
complete -F _ai_cli_copilot_completion copilot
complete -F _ai_cli_gemini_completion gemini
